theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0

title: Human Capital in the Nordic Countries
description: Repository for the HCNC project

show_downloads: false

permalink: /:slug

collections:
  articles:
    output: true
    layout: default
    permalink: /articles/:name
  sources:
    output: true
    layout: default
    permalink: /sources/:name

team:
  - surname: "Ford"
    firstname: "Nick"
    position: "PhD student"
    institution: "Lund University"
    role: ""
    website: "https://www.nickford.com"
    twitter: "nickford"
    github: "nickforddk"
  - surname: "Sharp"
    firstname: "Paul"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: "PI"
    website: "http://www.keynes.dk"
    twitter: "paulsharpechist"
    github: ""
  - surname: "Ranestad"
    firstname: "Kristin"
    position: "Senior lecturer"
    institution: "University of Oslo, Lund University"
    role: ""
    website: ""
    twitter: "KristinRanestad"
    github: ""
  - surname: "Dahl"
    firstname: "Christian Møller"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: "ChristianMDahl1"
    github: ""
  - surname: "Westermann"
    firstname: "Christian Emil"
    position: "PhD student"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: "chrisewester"
    github: "cewestermann"
  - surname: "Sommerseth"
    firstname: "Hilde Leikny"
    position: "Professor"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: "Norwegian Historical Data Centre"
    website: ""
    twitter: "hildeleikny"
    github: ""
  - surname: "Pedersen"
    firstname: "Bjørn-Richard"
    position: "Engineer"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Andersen"
    firstname: "Trygve"
    position: "Engineer"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Shvetsova"
    firstname: "Elena"
    position: "Research assistant"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Tonning"
    firstname: "Lise Wettergreen"
    position: "Research assistant"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: ""
    twitter: ""
    github: ""

ignore:
  - surname: ""
    firstname: ""
    position: ""
    institution: ""
    role: ""
    website: ""
    twitter: ""
    github: ""
