theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0

title: Human Capital in the Nordic Countries
description: Repository for the HCNC project

show_downloads: false

permalink: /:slug

collections:
  articles:
    output: true
    permalink: /articles/:name
  sources:
    output: true
    permalink: /:collection/:name
