theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0

title: Human Capital in the Nordic Countries
description: Education and its effects from the 18th century onwards

show_downloads: false

permalink: /:slug

collections:
  projects:
    output: true
    layout: default
    permalink: /projects/:name
  research:
    output: true
    layout: default
    permalink: /research/:name
  sources:
    output: true
    layout: default
    permalink: /sources/:name
  about:
    output: true
    layout: default
    permalink: /about/:name

team:
  - surname: "Ford"
    firstname: "Nick"
    username: "ford_n"
    position: "PhD student"
    institution: "Lund University"
    role: "Developer"
    website: "https://www.nickford.com"
    twitter: ""
    github: "nickforddk"
  - surname: "Sharp"
    firstname: "Paul"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: "http://www.keynes.dk"
    twitter: "paulsharpechist"
    github: ""
  - surname: "Ranestad"
    firstname: "Kristin"
    position: "Associate Professor"
    institution: "University of Oslo"
    role: ""
    website: "https://www.hf.uio.no/iakh/english/people/aca/history/tenured/krisrane/index.html"
    twitter: "KristinRanestad"
    github: ""
  - surname: "Dahl"
    firstname: "Christian Møller"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/en/persons/christian-møller-dahl"
    twitter: "ChristianMDahl1"
    github: ""
  - surname: "Westermann"
    firstname: "Christian Emil"
    position: "PhD student"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/da/persons/cew"
    twitter: ""
    github: "cewestermann"
  - surname: "Sommerseth"
    firstname: "Hilde Leikny"
    position: "Professor"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: "Norwegian Historical Data Centre"
    website: "https://en.uit.no/ansatte/person?p_document_id=400147"
    twitter: "hildeleikny"
    github: ""
  - surname: "Pedersen"
    firstname: "Bjørn-Richard"
    username: "pedersen_br"
    position: "Engineer"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: "https://en.uit.no/ansatte/bjorn-richard.pedersen"
    twitter: ""
    github: ""
  - surname: "Andersen"
    firstname: "Trygve"
    position: "Engineer"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: "https://en.uit.no/ansatte/trygve.andersen"
    twitter: ""
    github: ""
  - surname: "Boberg-Fazlic"
    firstname: "Nina"
    username: "boberg"
    position: "Junior Professor"
    institution: "TU Dortmund University"
    role: ""
    website: "https://wiwi.tu-dortmund.de/en/department/department-members/nina-boberg-fazlic/"
    twitter: ""
    github: ""
  - surname: "Görges"
    firstname: "Tom"
    position: "PhD student"
    institution: "TU Dortmund University"
    role: ""
    website: "https://wiwi.tu-dortmund.de/en/department/department-members/tom-goerges/"
    twitter: ""
    github: ""
  - surname: "Clark"
    firstname: "Gregory"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/da/persons/gclark"
    twitter: "GregoryClarkUCD"
    github: ""  
  - surname: "Vedel"
    firstname: "Christian"
    position: "Assistant Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/en/persons/christian-vedel"
    twitter: "ChristianVedel"
    github: "christianvedels"
  - surname: "Pedersen"
    firstname: "Maja Uhre"
    username: "pedersen_mu"
    position: "Assistant Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/da/persons/mup"
    twitter: ""
    github: ""
  - surname: "Hørlyk Kristensen"
    firstname: "Martin"
    position: "PhD student"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/da/persons/martin-kristensen"
    twitter: ""
    github: ""
  - surname: "Curtis"
    firstname: "Matthew"
    position: "Assistant Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: "https://portal.findresearcher.sdu.dk/en/persons/macu"
    twitter: "EconMattCurtis"
    github: ""  
  - surname: "Grapengeter"
    firstname: "Maret"
    position: "Research assistant"
    institution: "University of Oslo"
    role: ""
    website: ""
    twitter: ""
    github: ""  
  - surname: "Lien"
    firstname: "Trond"
    position: "Research assistant"
    institution: "University of Oslo"
    role: ""
    website: ""
    twitter: ""
    github: ""  
  - surname: "Nielsen"
    firstname: "Christian"
    position: "Research assistant"
    institution: "University of Southern Denmark"
    role: "Contact"
    website: "https://portal.findresearcher.sdu.dk/da/persons/cniel"
    twitter: ""
    github: "cniel98" 



ignore:
  - surname: ""
    firstname: ""
    username: ""
    position: ""
    institution: ""
    role: ""
    website: ""
    twitter: ""
    github: ""

